<template>
  <q-page class="bg-grey-1">
    <div v-if="result">
      <div class="row justify-center">
        <div class="col-12">

          <div class="text-subtitle1 q-pa-lg text-center">{{diagnosis()}}</div>
          <q-linear-progress  :value="result.resultPerc" :color="(result.resultStatus)?'red':'green'" class="q-mt-sm" />
        </div>
        <div class="col-6  q-pt-md" >
          <img :src="image" style="width: 100%"/>
        </div>

        <div class="row absolute-bottom text-center justify-center">
          <div class="text-subtitle2  q-pa-lg col-6 ">This is an Autogenerated Report. Use Caution!</div>
        </div>
      </div>
    </div>

    <div v-else class="absolute-center">
      <IconText icon="present_to_all" text="Please upload an xray image to see results"/>
    </div>

    <q-page-sticky position="bottom-right" :offset="[18, 18]">
      <q-btn fab icon="add" color="primary" @click="showUploadForm" />
    </q-page-sticky>

  </q-page>
</template>

<script>
  import IconText from "../../components/IconText";
  import UploadImageForm from "../../components/UploadImageForm";
  export default {
    name: 'PageIndex',
    components: {IconText},
    data(){
      return {
        image: '',
        result:{},
      }
    },
    props:{
      result:{
        default:false,
      }
    },
    methods:{
      showUploadForm(){
        const vm = this;
        this.$q.dialog({
          component: UploadImageForm,
          parent: this,
          text: 'something',
          // ...more.props...
        }).onOk((result) => {
          vm.result = result.data;
         vm.image = result.url;

        }).onCancel(() => {
          console.log('Cancel')
        }).onDismiss(() => {
          console.log('Called on OK or Cancel')
        })
      },
      diagnosis(){
        return `Diagnosis: The Patient ${this.result.patient.name} has test for chest pnemonia has returned ${this.result.resultStatus} with ${this.result.resultPerc}% accuracy`
      }
    },
  }
</script>
